[package]
name = "rust_rental_app"
version = "0.1.0"
edition = "2024"

[dependencies]
mysql = "*"  
dotenv = "0.15"
rouille = "3.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"  
